version: '3.3'

services:
  grafana:
    image: grafana/grafana:10.2.2
    container_name: grafana
    environment:
      - GF_SERVER_HTTP_ADDR=0.0.0.0
      - GF_SERVER_HTTP_PORT=3000
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "0.0.0.0:3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - grafana-net

volumes:
  grafana-data:
    driver: local

networks:
  grafana-net:
    driver: bridge

