---
- name: Install Docker on Kibana server
  hosts: kibana.ru-central1.internal
  become: true
  tasks:
    - name: Remove old elastic repository files
      shell: "rm -f /etc/apt/sources.list.d/*elastic*"
      become: true

    - name: Install prerequisites for community.docker
      apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: Install docker python library
      pip:
        name: docker

    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install prerequisite packages for Docker
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present

    - name: Create directory for apt keyrings
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker's official GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Update apt package index again
      apt:
        update_cache: yes

    - name: Install Docker Engine
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present

    - name: Configure Docker to use a registry mirror
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "registry-mirrors": ["https://huecker.io"]
          }
        owner: root
        group: root
        mode: '0644'

    - name: Add user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: restarted
        enabled: yes

- name: Deploy and run monitoring stack
  hosts: kibana.ru-central1.internal
  tasks:
    - name: Kill process on port 9100
      shell: "sudo kill -9 $(sudo lsof -t -i:9100) || true"
      become: true

    - name: Create monitoring directory on remote host
      file:
        path: /home/ubuntu/monitoring
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy docker-compose file and configurations
      copy:
        src: ../../monitoring/
        dest: /home/ubuntu/monitoring/
        owner: ubuntu
        group: ubuntu

    - name: Run docker-compose up
      community.docker.docker_compose_v2:
        project_src: /home/ubuntu/monitoring
      become: true