---
- name: Install and configure Kibana
  hosts: kibana.ru-central1.internal
  become: yes
  vars:
    kibana_version: "7.17.0"
    elasticsearch_host: "{{ hostvars['elasticsearch.ru-central1.internal']['ansible_default_ipv4']['address'] }}"

  tasks:
    - name: Add Elasticsearch GPG key
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Add Elasticsearch repository
      apt_repository:
        repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Kibana
      apt:
        name: kibana
        state: present

    - name: Configure Kibana
      template:
        src: ../templates/kibana.yml.j2
        dest: /etc/kibana/kibana.yml
        backup: yes
      notify: restart kibana

    - name: Enable and start Kibana
      systemd:
        name: kibana
        enabled: yes
        state: started
        daemon_reload: yes

    - name: Wait for Kibana to start
      wait_for:
        port: 5601
        host: localhost
        delay: 30
        timeout: 300

    - name: Open firewall for Kibana
      ufw:
        rule: allow
        port: '5601'
        proto: tcp

    - name: Install Nginx for reverse proxy
      apt:
        name: nginx
        state: present

    - name: Configure Nginx for Kibana
      template:
        src: ../templates/kibana_nginx.conf.j2
        dest: /etc/nginx/sites-available/kibana
      notify: restart nginx

    - name: Enable Kibana site
      file:
        src: /etc/nginx/sites-available/kibana
        dest: /etc/nginx/sites-enabled/kibana
        state: link
      notify: restart nginx

    - name: Remove default Nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: restart nginx

    - name: Enable and start Nginx
      systemd:
        name: nginx
        enabled: yes
        state: started

  handlers:
    - name: restart kibana
      systemd:
        name: kibana
        state: restarted

    - name: restart nginx
      systemd:
        name: nginx
        state: restarted