---
# Verify monitoring and logging system
- name: Verify monitoring and logging system
  hosts: localhost
  gather_facts: no
  vars:
    kibana_server: "{{ groups['kibana'][0] }}"
    web_servers: "{{ groups['web_servers'] }}"
    elasticsearch_server: "{{ groups['elasticsearch'][0] }}"
  
  tasks:
    - name: Check Prometheus is accessible
      uri:
        url: "http://{{ kibana_server }}:9090/api/v1/query?query=up"
        method: GET
        return_content: yes
      register: prometheus_check
      failed_when: prometheus_check.status != 200

    - name: Display Prometheus status
      debug:
        msg: "Prometheus is running and accessible at http://{{ kibana_server }}:9090"

    - name: Check Grafana is accessible
      uri:
        url: "http://{{ kibana_server }}:3000/api/health"
        method: GET
        return_content: yes
      register: grafana_check
      failed_when: grafana_check.status != 200

    - name: Display Grafana status
      debug:
        msg: "Grafana is running and accessible at http://{{ kibana_server }}:3000"

    - name: Check AlertManager is accessible
      uri:
        url: "http://{{ kibana_server }}:9093/api/v1/status"
        method: GET
        return_content: yes
      register: alertmanager_check
      failed_when: alertmanager_check.status != 200

    - name: Display AlertManager status
      debug:
        msg: "AlertManager is running and accessible at http://{{ kibana_server }}:9093"

    - name: Check Blackbox Exporter is accessible
      uri:
        url: "http://{{ kibana_server }}:9115/metrics"
        method: GET
        return_content: yes
      register: blackbox_check
      failed_when: blackbox_check.status != 200

    - name: Display Blackbox Exporter status
      debug:
        msg: "Blackbox Exporter is running and accessible at http://{{ kibana_server }}:9115"

    - name: Check Kibana is accessible
      uri:
        url: "http://{{ kibana_server }}:5601/api/status"
        method: GET
        return_content: yes
      register: kibana_check
      failed_when: kibana_check.status != 200

    - name: Display Kibana status
      debug:
        msg: "Kibana is running and accessible at http://{{ kibana_server }}:5601"

    - name: Check Elasticsearch is accessible
      uri:
        url: "http://{{ elasticsearch_server }}:9200/_cluster/health"
        method: GET
        return_content: yes
      register: elasticsearch_check
      failed_when: elasticsearch_check.status != 200

    - name: Display Elasticsearch status
      debug:
        msg: "Elasticsearch is running and accessible at http://{{ elasticsearch_server }}:9200"

- name: Verify Node Exporters on all servers
  hosts: all
  gather_facts: no
  tasks:
    - name: Check Node Exporter is running
      uri:
        url: "http://{{ ansible_default_ipv4.address }}:9100/metrics"
        method: GET
        return_content: yes
      register: node_exporter_check
      failed_when: node_exporter_check.status != 200

    - name: Display Node Exporter status
      debug:
        msg: "Node Exporter is running on {{ inventory_hostname }} at port 9100"

- name: Verify Nginx Exporters on web servers
  hosts: web_servers
  gather_facts: no
  tasks:
    - name: Check Nginx Exporter is running
      uri:
        url: "http://{{ ansible_default_ipv4.address }}:9113/metrics"
        method: GET
        return_content: yes
      register: nginx_exporter_check
      failed_when: nginx_exporter_check.status != 200

    - name: Display Nginx Exporter status
      debug:
        msg: "Nginx Exporter is running on {{ inventory_hostname }} at port 9113"

    - name: Check Nginx status endpoint
      uri:
        url: "http://{{ ansible_default_ipv4.address }}/nginx_status"
        method: GET
        return_content: yes
      register: nginx_status_check
      failed_when: nginx_status_check.status != 200

    - name: Display Nginx status endpoint
      debug:
        msg: "Nginx status endpoint is accessible on {{ inventory_hostname }}"

- name: Verify Elasticsearch Exporter
  hosts: elasticsearch
  gather_facts: no
  tasks:
    - name: Check Elasticsearch Exporter is running
      uri:
        url: "http://{{ ansible_default_ipv4.address }}:9114/metrics"
        method: GET
        return_content: yes
      register: elasticsearch_exporter_check
      failed_when: elasticsearch_exporter_check.status != 200

    - name: Display Elasticsearch Exporter status
      debug:
        msg: "Elasticsearch Exporter is running on {{ inventory_hostname }} at port 9114"

- name: Verify Filebeat on web servers
  hosts: web_servers
  gather_facts: no
  become: yes
  tasks:
    - name: Check Filebeat service status
      systemd:
        name: filebeat
      register: filebeat_status

    - name: Display Filebeat status
      debug:
        msg: "Filebeat is {{ filebeat_status.status.ActiveState }} on {{ inventory_hostname }}"

    - name: Check Filebeat logs
      command: journalctl -u filebeat --no-pager -n 5
      register: filebeat_logs
      changed_when: false

    - name: Display recent Filebeat logs
      debug:
        msg: "{{ filebeat_logs.stdout_lines }}"

- name: Final system verification summary
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Display monitoring system summary
      debug:
        msg: |
          ========================================
          MONITORING AND LOGGING SYSTEM SUMMARY
          ========================================
          
          ✅ MONITORING STACK (on Kibana server):
          - Prometheus: http://{{ groups['kibana'][0] }}:9090
          - Grafana: http://{{ groups['kibana'][0] }}:3000 (admin/admin)
          - AlertManager: http://{{ groups['kibana'][0] }}:9093
          - Blackbox Exporter: http://{{ groups['kibana'][0] }}:9115
          
          ✅ LOGGING STACK:
          - Elasticsearch: http://{{ groups['elasticsearch'][0] }}:9200
          - Kibana: http://{{ groups['kibana'][0] }}:5601
          
          ✅ EXPORTERS:
          - Node Exporter: Running on all servers (port 9100)
          - Nginx Exporter: Running on web servers (port 9113)
          - Elasticsearch Exporter: Running on Elasticsearch server (port 9114)
          
          ✅ LOG COLLECTION:
          - Filebeat: Running on web servers, sending logs to Elasticsearch
          
          ========================================
          All services are running and accessible!
          ========================================