---
- name: Configure web servers
  hosts: web_servers
  become: yes
  vars:
    nginx_user: www-data
    nginx_worker_processes: auto
    nginx_worker_connections: 1024

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Create web directory
      file:
        path: /var/www/html
        state: directory
        owner: "{{ nginx_user }}"
        group: "{{ nginx_user }}"
        mode: '0755'

    - name: Create index.html with server info
      template:
        src: ../templates/index.html.j2
        dest: /var/www/html/index.html
        owner: "{{ nginx_user }}"
        group: "{{ nginx_user }}"
        mode: '0644'
      notify: restart nginx

    - name: Configure Nginx
      template:
        src: ../templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        backup: yes
      notify: restart nginx

    - name: Configure Nginx site
      template:
        src: ../templates/default.j2
        dest: /etc/nginx/sites-available/default
        backup: yes
      notify: restart nginx

    - name: Enable and start Nginx
      systemd:
        name: nginx
        enabled: yes
        state: started

    - name: Open firewall for HTTP
      ufw:
        rule: allow
        port: '80'
        proto: tcp

    - name: Open firewall for HTTPS
      ufw:
        rule: allow
        port: '443'
        proto: tcp

  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted